# Generated by Django 2.2.4 on 2019-10-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='项目名称：xxx', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
