# Generated by Django 2.2.4 on 2019-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intro',
            field=models.TextField(default='在这里写项目详情'),
        ),
    ]
