# Generated by Django 2.2.4 on 2019-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='intro',
        ),
        migrations.AddField(
            model_name='project',
            name='describe',
            field=models.TextField(default='在这里写项目描述'),
        ),
    ]
